# Generated by Django 5.2.7 on 2026-03-21 11:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_phone_fields_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('late_threshold_minutes', models.IntegerField(default=15, help_text="Minutes past scheduled time to trigger 'late' alert")),
                ('missed_threshold_minutes', models.IntegerField(default=60, help_text="Minutes past scheduled time to mark as 'missed'")),
                ('upcoming_reminder_minutes', models.IntegerField(default=60, help_text='Minutes before appointment to send reminder')),
                ('overdue_followup_days', models.IntegerField(default=30, help_text='Days after last visit to trigger follow-up alert')),
                ('auto_resolve_on_checkin', models.BooleanField(default=True, help_text='Automatically resolve late/missed alerts when patient checks in')),
                ('auto_dismiss_after_days', models.IntegerField(default=7, help_text='Days after which to auto-dismiss unresolved alerts (0 = never)')),
                ('send_email_alerts', models.BooleanField(default=False)),
                ('send_sms_alerts', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_alert_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alert Configuration',
                'verbose_name_plural': 'Alert Configurations',
                'ordering': ['-is_active', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AppointmentAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_type', models.CharField(choices=[('missed', 'Missed Appointment'), ('late', 'Late Arrival'), ('upcoming', 'Upcoming Appointment'), ('overdue_followup', 'Overdue Follow-up')], max_length=20)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='active', max_length=15)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('trigger_time', models.DateTimeField(help_text='When the alert was triggered')),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('action_taken', models.TextField(blank=True, help_text='Actions taken to resolve the alert')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_alerts', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='patients.patient')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_alerts', to=settings.AUTH_USER_MODEL)),
                ('visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='patients.patientvisit')),
            ],
            options={
                'verbose_name': 'Appointment Alert',
                'verbose_name_plural': 'Appointment Alerts',
                'ordering': ['-trigger_time', '-created_at'],
                'indexes': [models.Index(fields=['status', 'alert_type'], name='patients_ap_status_0d930a_idx'), models.Index(fields=['trigger_time'], name='patients_ap_trigger_19073e_idx'), models.Index(fields=['-created_at'], name='patients_ap_created_4bc8b3_idx')],
            },
        ),
    ]
