# Generated by Django 5.2.7 on 2026-05-02 07:11

import precise_optics.file_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_alertconfiguration_appointmentalert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdocument',
            name='file',
            field=models.FileField(upload_to='patient_documents/', validators=[precise_optics.file_validators.validate_document_extension, precise_optics.file_validators.validate_file_size]),
        ),
    ]
