# Generated by Django 5.2.7 on 2026-03-21 09:17

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0002_phone_fields_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('referral_number', models.CharField(help_text='Unique referral tracking number', max_length=50, unique=True)),
                ('direction', models.CharField(choices=[('outgoing', 'Outgoing (To Specialist)'), ('incoming', 'Incoming (From Provider)')], max_length=20)),
                ('reason', models.CharField(choices=[('specialist_opinion', 'Specialist Opinion Required'), ('surgical_evaluation', 'Surgical Evaluation'), ('advanced_imaging', 'Advanced Imaging/Diagnostics'), ('subspecialty_care', 'Subspecialty Care'), ('treatment_not_available', 'Treatment Not Available Here'), ('patient_request', 'Patient Request'), ('second_opinion', 'Second Opinion'), ('emergency', 'Emergency Care'), ('follow_up', 'Follow-up Care'), ('other', 'Other')], max_length=50)),
                ('urgency', models.CharField(choices=[('routine', 'Routine'), ('soon', 'Soon (2-4 weeks)'), ('urgent', 'Urgent (within 1 week)'), ('emergency', 'Emergency (same day)')], default='routine', max_length=20)),
                ('clinical_summary', models.TextField(help_text='Clinical summary and reason for referral')),
                ('relevant_history', models.TextField(blank=True, help_text='Relevant medical history')),
                ('current_medications', models.TextField(blank=True)),
                ('allergies', models.TextField(blank=True)),
                ('specific_questions', models.TextField(blank=True, help_text='Specific questions or concerns to address')),
                ('requested_services', models.TextField(blank=True, help_text='Specific tests or procedures requested')),
                ('current_status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('sent', 'Sent'), ('acknowledged', 'Acknowledged'), ('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('status_notes', models.TextField(blank=True)),
                ('referral_date', models.DateField(help_text='Date referral was created')),
                ('sent_date', models.DateField(blank=True, null=True)),
                ('acknowledged_date', models.DateField(blank=True, null=True)),
                ('appointment_date', models.DateField(blank=True, null=True)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('outcome_summary', models.TextField(blank=True, help_text='Summary of referral outcome')),
                ('follow_up_required', models.BooleanField(default=False)),
                ('follow_up_notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='referrals_created', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='referrals', to='patients.patient')),
                ('referred_by', models.ForeignKey(help_text='Staff member who made the referral', on_delete=django.db.models.deletion.PROTECT, related_name='referrals_made', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Staff member who reviewed/approved', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='referrals_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-referral_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReferralDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('referral_letter', 'Referral Letter'), ('test_results', 'Test Results'), ('imaging', 'Imaging/Scans'), ('medical_records', 'Medical Records'), ('consent_form', 'Consent Form'), ('response_letter', 'Response Letter'), ('discharge_summary', 'Discharge Summary'), ('other', 'Other')], max_length=30)),
                ('file', models.FileField(upload_to='referral_documents/%Y/%m/')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('referral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='referrals.referral')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='referral_documents_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ReferralResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('response_type', models.CharField(choices=[('acknowledgment', 'Acknowledgment'), ('appointment_scheduled', 'Appointment Scheduled'), ('additional_info_requested', 'Additional Info Requested'), ('clinical_report', 'Clinical Report'), ('discharge_summary', 'Discharge Summary'), ('follow_up_recommendation', 'Follow-up Recommendation'), ('outcome_report', 'Outcome Report'), ('rejection', 'Referral Rejected'), ('other', 'Other')], max_length=40)),
                ('response_date', models.DateField()),
                ('response_content', models.TextField(help_text='Content of the response')),
                ('appointment_date', models.DateTimeField(blank=True, null=True)),
                ('appointment_location', models.CharField(blank=True, max_length=255)),
                ('additional_tests_required', models.TextField(blank=True)),
                ('recommendations', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='referral_responses_created', to=settings.AUTH_USER_MODEL)),
                ('referral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='referrals.referral')),
            ],
            options={
                'ordering': ['-response_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReferralSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name of provider/facility', max_length=200)),
                ('source_type', models.CharField(choices=[('ophthalmologist', 'Ophthalmologist'), ('optometrist', 'Optometrist'), ('hospital', 'Hospital'), ('clinic', 'Clinic'), ('gp', 'General Practitioner'), ('specialist', 'Medical Specialist'), ('other', 'Other')], max_length=20)),
                ('contact_person', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('phone', models.CharField(blank=True, help_text='Phone number', max_length=20, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{9,15}$')])),
                ('fax', models.CharField(blank=True, max_length=20)),
                ('address_line1', models.CharField(blank=True, max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(default='United Kingdom', max_length=100)),
                ('specialties', models.TextField(blank=True, help_text='Areas of specialty')),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_preferred', models.BooleanField(default=False, help_text='Preferred referral partner')),
                ('total_referrals_sent', models.IntegerField(default=0)),
                ('total_referrals_received', models.IntegerField(default=0)),
                ('average_response_time_days', models.DecimalField(blank=True, decimal_places=1, help_text='Average days to respond', max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='referral_sources_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='referral',
            name='referral_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='referrals', to='referrals.referralsource'),
        ),
        migrations.AddIndex(
            model_name='referralsource',
            index=models.Index(fields=['source_type', 'is_active'], name='referrals_r_source__15d299_idx'),
        ),
        migrations.AddIndex(
            model_name='referralsource',
            index=models.Index(fields=['is_preferred', 'is_active'], name='referrals_r_is_pref_31bf06_idx'),
        ),
        migrations.AddIndex(
            model_name='referral',
            index=models.Index(fields=['patient', 'current_status'], name='referrals_r_patient_b72309_idx'),
        ),
        migrations.AddIndex(
            model_name='referral',
            index=models.Index(fields=['referral_source', 'direction'], name='referrals_r_referra_f7e198_idx'),
        ),
        migrations.AddIndex(
            model_name='referral',
            index=models.Index(fields=['current_status', 'urgency'], name='referrals_r_current_49c512_idx'),
        ),
        migrations.AddIndex(
            model_name='referral',
            index=models.Index(fields=['referral_date'], name='referrals_r_referra_126e05_idx'),
        ),
    ]
