# Generated by Django 5.2.7 on 2025-10-15 14:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatment',
            name='assisting_staff',
            field=models.ManyToManyField(blank=True, limit_choices_to={'user_type__in': ['doctor', 'nurse', 'technician']}, related_name='assisted_treatments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='primary_surgeon',
            field=models.ForeignKey(limit_choices_to={'user_type__in': ['doctor', 'admin']}, on_delete=django.db.models.deletion.PROTECT, related_name='primary_treatments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='treatmentfollowup',
            name='assessed_by',
            field=models.ForeignKey(limit_choices_to={'user_type__in': ['doctor', 'nurse', 'technician']}, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
