# Generated by Django 5.2.7 on 2026-05-02 07:11

import precise_optics.file_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatments', '0002_alter_treatment_assisting_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatmentdocument',
            name='file',
            field=models.FileField(upload_to='treatments/documents/%Y/%m/%d/', validators=[precise_optics.file_validators.validate_document_extension, precise_optics.file_validators.validate_file_size]),
        ),
    ]
