# Generated by Django 5.2.7 on 2026-05-02 07:11

import precise_optics.file_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultationdocument',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='consultation_documents/', validators=[precise_optics.file_validators.validate_document_extension, precise_optics.file_validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='consultationimage',
            name='image',
            field=models.ImageField(upload_to='consultation_images/', validators=[precise_optics.file_validators.validate_image_extension, precise_optics.file_validators.validate_file_size]),
        ),
    ]
