# Generated by Django 5.2.7 on 2026-05-10 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0002_alter_consultationdocument_file_and_more'),
        ('patients', '0004_alter_patientdocument_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='visit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultations', to='patients.patientvisit'),
        ),
    ]
