# Generated by Django 5.2.7 on 2025-11-02 21:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0003_alter_medication_manufacturer'),
        ('protocols', '0002_enhanced_protocol_steps'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='protocolstep',
            name='default_next_step',
            field=models.ForeignKey(blank=True, help_text='Default next step if no branching or branch conditions not met', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preceding_steps', to='protocols.protocolstep'),
        ),
        migrations.AlterField(
            model_name='protocolstep',
            name='branch_condition_type',
            field=models.CharField(blank=True, choices=[('test_result', 'Based on Test Result'), ('outcome', 'Based on Step Outcome'), ('measurement', 'Based on Measurement'), ('adverse_event', 'Based on Adverse Event'), ('yes_no', 'Yes/No Decision'), ('met_not_met', 'Met/Not Met Criteria'), ('free_text', 'Free Text Evaluation'), ('manual', 'Manual Decision')], help_text='What determines which branch to follow', max_length=50),
        ),
        migrations.AlterField(
            model_name='protocolstep',
            name='branch_logic',
            field=models.JSONField(blank=True, default=dict, help_text="Branching conditions and next step mappings.\n        Format: {\n            'conditions': [\n                {'result': 'yes', 'next_step': 2, 'label': 'If improved'},\n                {'result': 'no', 'next_step': 3, 'label': 'If no improvement'}\n            ],\n            'evaluation_field': 'result_value',\n            'default_next_step': 4\n        }"),
        ),
        migrations.AlterField(
            model_name='protocolstep',
            name='medication',
            field=models.ForeignKey(blank=True, help_text='Primary medication (legacy - use ProtocolStepMedication for multiple)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='protocol_steps', to='medications.medication'),
        ),
        migrations.AlterField(
            model_name='protocolstep',
            name='required_test_type',
            field=models.CharField(blank=True, help_text='Type of test required (legacy)', max_length=100),
        ),
        migrations.AlterField(
            model_name='protocolstep',
            name='timing_days',
            field=models.PositiveIntegerField(help_text='Days from start/previous step, or interval for recurring'),
        ),
        migrations.CreateModel(
            name='ProtocolStepResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('result_type', models.CharField(choices=[('yes_no', 'Yes/No'), ('met_not_met', 'Met/Not Met'), ('numeric', 'Numeric Value'), ('free_text', 'Free Text'), ('scale', 'Scale (1-10)'), ('multiple_choice', 'Multiple Choice')], default='free_text', max_length=20)),
                ('result_label', models.CharField(help_text="Label for this result (e.g., 'IOP improved?', 'Vision assessment')", max_length=200)),
                ('result_value_text', models.TextField(blank=True, help_text='Free text result')),
                ('result_value_numeric', models.DecimalField(blank=True, decimal_places=2, help_text='Numeric result value', max_digits=10, null=True)),
                ('result_value_choice', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('met', 'Met'), ('not_met', 'Not Met'), ('improved', 'Improved'), ('stable', 'Stable'), ('worsened', 'Worsened'), ('n/a', 'Not Applicable')], help_text='Predefined choice result', max_length=50)),
                ('result_value_json', models.JSONField(blank=True, default=dict, help_text='Complex result data (multiple values, measurements)')),
                ('evaluation_notes', models.TextField(blank=True, help_text='Clinical interpretation of result')),
                ('meets_criteria', models.BooleanField(blank=True, help_text='Does result meet expected criteria?', null=True)),
                ('triggers_branch', models.BooleanField(default=False, help_text='Does this result trigger a branch in the protocol?')),
                ('branch_taken', models.CharField(blank=True, help_text='Which branch was taken based on this result', max_length=100)),
                ('evaluated_at', models.DateTimeField(auto_now_add=True)),
                ('evaluated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='protocol_step_evaluations', to=settings.AUTH_USER_MODEL)),
                ('next_step_override', models.ForeignKey(blank=True, help_text='Next step if branching logic applies', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='result_triggered_steps', to='protocols.protocolstep')),
                ('step_completion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='protocols.protocolstepcompletion')),
            ],
            options={
                'verbose_name': 'Protocol Step Result',
                'verbose_name_plural': 'Protocol Step Results',
                'ordering': ['step_completion', 'evaluated_at'],
            },
        ),
    ]
