# Generated by Django 5.2.7 on 2026-05-02 07:11

import precise_optics.file_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocols', '0003_protocolstep_default_next_step_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consentform',
            name='consent_document',
            field=models.FileField(blank=True, help_text='Signed consent form', null=True, upload_to='consent_forms/', validators=[precise_optics.file_validators.validate_document_extension, precise_optics.file_validators.validate_file_size]),
        ),
    ]
