# Generated by Django 5.2.7 on 2026-07-04 07:33

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consultations', '0003_make_visit_optional'),
        ('medications', '0004_medicationrecall'),
        ('patients', '0004_alter_patientdocument_file'),
        ('treatments', '0003_alter_treatmentdocument_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientOutcomeReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_date', models.DateField(help_text='Date the questionnaire was completed')),
                ('vision_quality_score', models.IntegerField(help_text='Overall vision quality: 1 (very poor) – 10 (excellent)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('pain_discomfort_score', models.IntegerField(help_text='Pain or eye discomfort: 0 (none) – 10 (severe)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('light_sensitivity_score', models.IntegerField(help_text='Light sensitivity / glare: 0 (none) – 10 (severe)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('daily_activities_score', models.IntegerField(help_text='Ability to perform daily activities: 1 (very limited) – 10 (no limitation)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('reading_ability_score', models.IntegerField(help_text='Reading ability: 1 (unable) – 10 (no difficulty)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('driving_ability_score', models.IntegerField(blank=True, help_text='Driving ability: 1 (unable) – 10 (no difficulty). Leave blank if not applicable.', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('treatment_satisfaction', models.CharField(choices=[('very_satisfied', 'Very Satisfied'), ('satisfied', 'Satisfied'), ('neutral', 'Neutral'), ('dissatisfied', 'Dissatisfied'), ('very_dissatisfied', 'Very Dissatisfied')], help_text='Overall satisfaction with current treatment', max_length=20)),
                ('side_effects_reported', models.TextField(blank=True, help_text='Describe any side effects the patient has experienced')),
                ('side_effect_severity', models.CharField(choices=[('none', 'None'), ('mild', 'Mild – noticeable but not interfering'), ('moderate', 'Moderate – affecting daily life'), ('severe', 'Severe – significantly disabling')], default='none', max_length=10)),
                ('patient_comments', models.TextField(blank=True, help_text="Any additional comments from the patient's perspective")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('completed_by', models.ForeignKey(help_text='Staff member who recorded this questionnaire', on_delete=django.db.models.deletion.PROTECT, related_name='outcome_reports_entered', to=settings.AUTH_USER_MODEL)),
                ('consultation', models.ForeignKey(blank=True, help_text='Consultation this report relates to (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outcome_reports', to='consultations.consultation')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcome_reports', to='patients.patient')),
                ('prescription', models.ForeignKey(blank=True, help_text='Prescription being evaluated (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outcome_reports', to='medications.prescription')),
                ('treatment', models.ForeignKey(blank=True, help_text='Treatment being evaluated (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outcome_reports', to='treatments.treatment')),
            ],
            options={
                'verbose_name': 'Patient Outcome Report',
                'verbose_name_plural': 'Patient Outcome Reports',
                'ordering': ['-report_date', '-created_at'],
            },
        ),
    ]
