# Generated by Django 5.2.7 on 2025-10-05 08:49

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('generic_name', models.CharField(max_length=200)),
                ('brand_names', models.TextField(help_text='Comma-separated brand names')),
                ('medication_type', models.CharField(choices=[('eye_drop', 'Eye Drop'), ('ointment', 'Eye Ointment'), ('tablet', 'Tablet'), ('injection', 'Injection'), ('gel', 'Eye Gel'), ('insert', 'Eye Insert'), ('solution', 'Solution')], max_length=20)),
                ('therapeutic_class', models.CharField(choices=[('antibiotic', 'Antibiotic'), ('anti_inflammatory', 'Anti-inflammatory'), ('steroid', 'Steroid'), ('antiglaucoma', 'Anti-glaucoma'), ('mydriatic', 'Mydriatic'), ('anesthetic', 'Anesthetic'), ('antiviral', 'Antiviral'), ('antifungal', 'Antifungal'), ('lubricant', 'Lubricant'), ('vasodilator', 'Vasodilator'), ('anti_vegf', 'Anti-VEGF'), ('immunosuppressive', 'Immunosuppressive')], max_length=30)),
                ('strength', models.CharField(help_text='e.g., 0.5%, 10mg/ml', max_length=100)),
                ('active_ingredients', models.TextField()),
                ('description', models.TextField()),
                ('indications', models.TextField(help_text='Medical conditions this drug treats')),
                ('contraindications', models.TextField(help_text='When not to use this drug')),
                ('side_effects', models.TextField()),
                ('standard_dosage', models.CharField(help_text='Standard dosage instructions', max_length=200)),
                ('maximum_daily_dose', models.CharField(max_length=100)),
                ('storage_temperature', models.CharField(max_length=100)),
                ('shelf_life_months', models.PositiveIntegerField()),
                ('special_handling', models.TextField(blank=True)),
                ('manufacturer', models.CharField(max_length=200)),
                ('batch_number', models.CharField(blank=True, max_length=100)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('approval_status', models.BooleanField(default=True)),
                ('current_stock', models.PositiveIntegerField(default=0)),
                ('minimum_stock_level', models.PositiveIntegerField(default=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Medication',
                'verbose_name_plural': 'Medications',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MedicationAdministration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('administration_time', models.DateTimeField()),
                ('route', models.CharField(choices=[('topical', 'Topical (Eye Drop/Ointment)'), ('oral', 'Oral'), ('injection_iv', 'Intravenous Injection'), ('injection_im', 'Intramuscular Injection'), ('injection_subconjunctival', 'Subconjunctival Injection'), ('injection_intravitreal', 'Intravitreal Injection'), ('injection_periocular', 'Periocular Injection')], max_length=30)),
                ('dosage_administered', models.CharField(max_length=100)),
                ('eye_side', models.CharField(blank=True, choices=[('both', 'Both Eyes'), ('left', 'Left Eye'), ('right', 'Right Eye')], max_length=10, null=True)),
                ('notes', models.TextField(blank=True)),
                ('adverse_reactions', models.TextField(blank=True)),
                ('verification_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('administered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='administered_medications', to=settings.AUTH_USER_MODEL)),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medications.medication')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='administrations', to='patients.patient')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_administrations', to=settings.AUTH_USER_MODEL)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='administrations', to='patients.patientvisit')),
            ],
            options={
                'verbose_name': 'Medication Administration',
                'verbose_name_plural': 'Medication Administrations',
                'ordering': ['-administration_time'],
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prescription_number', models.CharField(max_length=50, unique=True)),
                ('diagnosis', models.TextField()),
                ('instructions', models.TextField(help_text='General instructions for the patient')),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='active', max_length=20)),
                ('date_prescribed', models.DateTimeField(auto_now_add=True)),
                ('valid_until', models.DateField()),
                ('doctor_notes', models.TextField(blank=True)),
                ('pharmacy_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='patients.patient')),
                ('prescribing_doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to=settings.AUTH_USER_MODEL)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='patients.patientvisit')),
            ],
            options={
                'verbose_name': 'Prescription',
                'verbose_name_plural': 'Prescriptions',
                'ordering': ['-date_prescribed'],
            },
        ),
        migrations.CreateModel(
            name='PrescriptionItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dosage', models.CharField(help_text='e.g., 1 drop, 2 tablets', max_length=100)),
                ('frequency', models.CharField(choices=[('once_daily', 'Once daily'), ('twice_daily', 'Twice daily'), ('three_times_daily', 'Three times daily'), ('four_times_daily', 'Four times daily'), ('every_2_hours', 'Every 2 hours'), ('every_4_hours', 'Every 4 hours'), ('every_6_hours', 'Every 6 hours'), ('every_8_hours', 'Every 8 hours'), ('as_needed', 'As needed'), ('bedtime', 'At bedtime'), ('morning', 'Morning only'), ('custom', 'Custom frequency')], max_length=20)),
                ('custom_frequency', models.CharField(blank=True, max_length=200)),
                ('duration_days', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(365)])),
                ('eye_side', models.CharField(choices=[('both', 'Both Eyes'), ('left', 'Left Eye'), ('right', 'Right Eye')], default='both', max_length=10)),
                ('special_instructions', models.TextField(blank=True)),
                ('quantity_prescribed', models.PositiveIntegerField(help_text='Total quantity to dispense')),
                ('quantity_dispensed', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medications.medication')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='medications.prescription')),
            ],
            options={
                'verbose_name': 'Prescription Item',
                'verbose_name_plural': 'Prescription Items',
            },
        ),
        migrations.CreateModel(
            name='DrugAllergy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reaction_type', models.CharField(choices=[('allergic', 'Allergic Reaction'), ('adverse', 'Adverse Drug Reaction'), ('intolerance', 'Drug Intolerance'), ('interaction', 'Drug Interaction')], max_length=20)),
                ('severity', models.CharField(choices=[('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe'), ('life_threatening', 'Life Threatening')], max_length=20)),
                ('symptoms', models.TextField(help_text='Description of allergic symptoms')),
                ('first_occurrence_date', models.DateField()),
                ('last_occurrence_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('documented_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drug_allergies', to='patients.patient')),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allergic_patients', to='medications.medication')),
            ],
            options={
                'verbose_name': 'Drug Allergy',
                'verbose_name_plural': 'Drug Allergies',
                'unique_together': {('patient', 'medication')},
            },
        ),
    ]
