# Generated by Django 5.2.7 on 2025-11-01 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0002_alter_medication_manufacturer_manufacturer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='manufacturer',
            field=models.CharField(db_column='manufacturer_legacy', help_text='Manufacturer name (legacy field)', max_length=200),
        ),
    ]
