# Generated by Django 5.2.7 on 2025-11-01 11:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0002_phone_fields_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalCondition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text='Unique condition code', max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('retinal', 'Retinal Disorders'), ('glaucoma', 'Glaucoma'), ('cataract', 'Cataracts'), ('corneal', 'Corneal Disorders'), ('diabetic', 'Diabetic Eye Disease'), ('vascular', 'Vascular Disorders'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField()),
                ('symptoms', models.TextField(help_text='Common symptoms')),
                ('risk_factors', models.TextField(help_text='Known risk factors')),
                ('typical_progression', models.TextField(help_text='How the condition typically progresses')),
                ('standard_treatments', models.TextField(help_text='Standard treatment approaches')),
                ('prognosis', models.TextField(help_text='Typical outcomes and prognosis')),
                ('has_standard_protocol', models.BooleanField(default=False)),
                ('protocol_description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_conditions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Medical Condition',
                'verbose_name_plural': 'Medical Conditions',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PatientCondition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('diagnosis_date', models.DateField()),
                ('severity', models.CharField(choices=[('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe'), ('very_severe', 'Very Severe')], max_length=20)),
                ('eye_affected', models.CharField(choices=[('both', 'Both Eyes'), ('left', 'Left Eye Only'), ('right', 'Right Eye Only')], max_length=10)),
                ('current_status', models.CharField(choices=[('newly_diagnosed', 'Newly Diagnosed'), ('active', 'Active'), ('stable', 'Stable'), ('progressing', 'Progressing'), ('improving', 'Improving'), ('resolved', 'Resolved'), ('managed', 'Under Management')], default='newly_diagnosed', max_length=20)),
                ('initial_measurements', models.JSONField(blank=True, default=dict, help_text='Initial measurements at diagnosis (e.g., visual acuity, IOP)')),
                ('treatment_plan', models.TextField(blank=True)),
                ('medications_prescribed', models.TextField(blank=True)),
                ('last_assessment_date', models.DateField(blank=True, null=True)),
                ('next_assessment_date', models.DateField(blank=True, null=True)),
                ('diagnosis_notes', models.TextField(blank=True)),
                ('patient_notes', models.TextField(blank=True, help_text='Patient-specific notes')),
                ('is_active', models.BooleanField(default=True)),
                ('resolved_date', models.DateField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patient_cases', to='conditions.medicalcondition')),
                ('diagnosed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='diagnosed_conditions', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_conditions', to='patients.patient')),
            ],
            options={
                'verbose_name': 'Patient Condition',
                'verbose_name_plural': 'Patient Conditions',
                'ordering': ['-diagnosis_date'],
                'unique_together': {('patient', 'condition', 'diagnosis_date')},
            },
        ),
        migrations.CreateModel(
            name='ConditionProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assessment_date', models.DateField()),
                ('assessment_type', models.CharField(choices=[('routine', 'Routine Follow-up'), ('urgent', 'Urgent Assessment'), ('post_treatment', 'Post-Treatment Review'), ('protocol_step', 'Protocol Milestone'), ('emergency', 'Emergency Assessment')], max_length=20)),
                ('status_change', models.CharField(choices=[('improved', 'Improved'), ('stable', 'Stable/No Change'), ('worsened', 'Worsened'), ('new_symptoms', 'New Symptoms'), ('resolved', 'Resolved')], max_length=20)),
                ('severity_at_assessment', models.CharField(choices=[('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe'), ('very_severe', 'Very Severe')], max_length=20)),
                ('measurements', models.JSONField(default=dict, help_text='Current measurements (visual acuity, IOP, OCT results, etc.)')),
                ('clinical_findings', models.TextField()),
                ('subjective_symptoms', models.TextField(blank=True, help_text='Patient-reported symptoms')),
                ('treatment_changes', models.TextField(blank=True)),
                ('medications_adjusted', models.BooleanField(default=False)),
                ('next_assessment_date', models.DateField(blank=True, null=True)),
                ('next_assessment_reason', models.CharField(blank=True, max_length=200)),
                ('assessment_notes', models.TextField()),
                ('images_attached', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='condition_assessments', to=settings.AUTH_USER_MODEL)),
                ('patient_condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='conditions.patientcondition')),
            ],
            options={
                'verbose_name': 'Condition Progress',
                'verbose_name_plural': 'Condition Progress Records',
                'ordering': ['-assessment_date'],
            },
        ),
        migrations.CreateModel(
            name='ConditionDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('scan', 'Diagnostic Scan'), ('report', 'Medical Report'), ('image', 'Clinical Image'), ('consent', 'Consent Form'), ('referral', 'Referral Document'), ('protocol', 'Protocol Document'), ('other', 'Other')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='condition_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('progress_record', models.ForeignKey(blank=True, help_text='Link to specific progress assessment if applicable', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='conditions.conditionprogress')),
                ('patient_condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='conditions.patientcondition')),
            ],
            options={
                'verbose_name': 'Condition Document',
                'verbose_name_plural': 'Condition Documents',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
